version: 2.1

commands:
  attach_to_workspace:
    steps:
      - attach_workspace:
          at: ~/

  publish_docker_images:
    parameters:
      repo:
        type: string
      tag:
        type: string
    steps:
      - run:
          name: Build image
          command: |
            make docker-otelcontribcol
            docker tag otelcontribcol:latest otel/<< parameters.repo >>:<< parameters.tag >>
            docker tag otelcontribcol:latest otel/<< parameters.repo >>:latest
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
      - run:
          name: Push image
          command: |
            docker push sumologic/<< parameters.repo >>:<< parameters.tag >>
            docker push sumologic/<< parameters.repo >>:latest

workflows:
  version: 2
  build-publish:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9].[0-9].[0-9]+.*/

jobs:
  build:
    docker:
      - image: cimg/go:1.14
    steps:
      - checkout
      - run:
          name: Install bazzar
          command: sudo apt update && sudo apt-get install bzr -y
      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - cimg-go-pkg-mod-{{ checksum "go.sum" }}-v2
      - run:
          name: Install tools
          command: make install-tools
      - run:
          name: create modules dir
          command: mkdir -p /home/circleci/go/pkg/mod
      - run:
          name: Verify
          command: make ci
      - run:
          name: Build collector 
          command: make otelcontribcol
      - save_cache:
          key: cimg-go-pkg-mod-{{ checksum "go.sum" }}-v2
          paths:
            - "/home/circleci/go/pkg/mod"
      - store_artifacts:
          path: testbed/tests/results
      - store_test_results:
          path: testbed/tests/results/junit
      - persist_to_workspace:
          root: ~/
          paths:
            - go
            - project
  publish:
    docker:
      - image: cimg/go:1.14
    steps:
      - attach_to_workspace
      - setup_remote_docker
      - publish_docker_images:
          repo: opentelemetry-collector-contrib
          tag: ${CIRCLE_TAG:1}
      - run:
          name: Build image
          command: |
            make docker-otelcontribcol
            docker tag otelcontribcol:latest sumologic/opentelemetry-collector:${CIRCLE_TAG:1}
            docker tag otelcontribcol:latest sumologic/opentelemetry-collector:latest
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
      - run:
          name: Push image
          command: |
            docker push sumologic/opentelemetry-collector:${CIRCLE_TAG:1}
            docker push sumologic/opentelemetry-collector:latest
