receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  otlphttp:
    traces_endpoint: $SUMOLOGIC_HTTP_TRACES_ENDPOINT_URL

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
